#!/usr/bin/env bash
set -euo pipefail

# ==============================================================================
# TrackStar PDS Automated Setup Script for Ubuntu / Debian Linux
# ==============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

echo "========================================================"
echo "   TrackStar AT Protocol Personal Data Server (PDS)     "
echo "   Automated Setup & Secrets Generator                  "
echo "========================================================"
echo ""

# 1. Prompt or accept domain from argument
DOMAIN="${1:-}"
if [ -z "$DOMAIN" ]; then
    read -rp "Enter your PDS domain / subdomain (e.g. pds.example.com): " DOMAIN
fi

if [ -z "$DOMAIN" ]; then
    echo "❌ Error: Domain cannot be empty."
    exit 1
fi

echo ">> Configuring PDS for domain: $DOMAIN"
echo ""

# 2. Check dependencies
command -v docker >/dev/null 2>&1 || { echo "❌ Docker is required but not installed. Please install Docker first: https://docs.docker.com/engine/install/ubuntu/"; exit 1; }
command -v openssl >/dev/null 2>&1 || { echo "❌ OpenSSL is required but not installed."; exit 1; }

# 3. Generate Cryptographic Secrets
echo ">> Generating secure cryptographic secrets..."

# Admin Password
ADMIN_PASSWORD=$(openssl rand -hex 16)

# JWT Secret
JWT_SECRET=$(openssl rand -hex 32)

# K256 PLC Rotation Key (32-byte hex)
if command -v xxd >/dev/null 2>&1; then
    PLC_ROTATION_KEY=$(openssl ecparam --name secp256k1 --genkey --noout --outform DER | tail -c +8 | head -c 32 | xxd -p -c 32)
else
    # Fallback to 32 random bytes in hex
    PLC_ROTATION_KEY=$(openssl rand -hex 32)
fi

# 4. Prepare data directories
mkdir -p data/blocks
chmod 700 data

# 5. Create or update .env file
ENV_FILE=".env"
if [ -f "$ENV_FILE" ]; then
    echo "⚠️  Existing .env found. Backing up to .env.backup..."
    cp "$ENV_FILE" .env.backup
fi

cat <<EOF > "$ENV_FILE"
# Generated by TrackStar PDS Setup on $(date)
PDS_HOSTNAME=$DOMAIN
PDS_PUBLIC_URL=https://$DOMAIN
PDS_ADMIN_PASSWORD=$ADMIN_PASSWORD
PDS_JWT_SECRET=$JWT_SECRET
PDS_PLC_ROTATION_KEY_K256_PRIVATE_KEY_HEX=$PLC_ROTATION_KEY
PDS_INVITE_REQUIRED=true
PDS_BLOB_UPLOAD_LIMIT=52428800
PDS_DID_PLC_URL=https://plc.directory
PDS_BSKY_APP_VIEW_URL=https://api.bsky.app
PDS_BSKY_APP_VIEW_DID=did:web:api.bsky.app
PDS_REPORT_SERVICE_URL=https://mod.bsky.app
PDS_REPORT_SERVICE_DID=did:plc:ar7c4by46qzaona2a2vptpon
PDS_CRAWLERS=https://bsky.network
LOG_ENABLED=true
EOF

chmod 600 "$ENV_FILE"

echo ""
echo "✅ Setup complete! Configuration written to .env"
echo ""
echo "========================================================"
echo "                  NEXT STEPS CHECKLIST                  "
echo "========================================================"
echo "1. DNS Record:"
echo "   Create an 'A' record in your DNS provider:"
echo "   Host: $DOMAIN"
echo "   Value: <Your Server's Public IP>"
echo ""
echo "2. Port Forwarding:"
echo "   Ensure your router forwards ports 80 & 443 to this Ubuntu server."
echo ""
echo "3. Start Services:"
echo "   docker compose up -d"
echo ""
echo "4. Admin Credentials Saved:"
echo "   PDS URL:         https://$DOMAIN"
echo "   Admin Password:  $ADMIN_PASSWORD"
echo "   (Saved in $SCRIPT_DIR/.env)"
echo ""
echo "5. Create Your User Account:"
echo "   Run: ./manage.sh create-account"
echo "========================================================"
